#!/usr/bin/php
<?php

require_once(dirname(__FILE__) . '/common.php');

if($argc != 2) {
    die("Usage: template <dir|file>\n");
}

$config = get_config('configure');

if(is_dir($argv[1])) {
    $files_dir = $argv[1];
    $files = scandir($files_dir);

    foreach($files as $file) {
        $file = realpath($files_dir . '/' . $file);

        if(!is_file($file)) {
            continue;
        }

        template_file($file, $config);
    }
}
elseif(is_file($argv[1])) {
    template_file($file, $config);
}
